#!/bin/bash

mkdir -p build
# object code is stored in a build folder
function compile() {
  g++ -std=c++11 -I./ -c src/$1.cpp -o build/$1.o
}

compile Customer
compile Order
compile ordering

g++ -I./build build/ordering.o build/Customer.o build/Order.o -o ordering